### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Abrahamlet** [kartik-v/krajee-markdown-editor#1]
Where's the documentation for this plugin? The links provided in the demo section of the README file don't work. :slightly_frowning_face:

**Comment by kartik-v** [comment]
Documentation needs to be created. This is an extension that has many bells and whistles and features and not got time to do it... will do it when I get time. Any help is appreciated.

**Comment by kartik-v** [comment]
Docs at http://plugins.krajee.com/markdown-editor
