### ISSUE TITLE
Bootstrap compatibility 5.2.3

### ISSUE THREAD

**Issue by neecride** [kartik-v/krajee-markdown-editor#11]
Hello, sorry for understanding i am fr

i use boostrap v5 and I generate editor

```
    </script>
        <script stype="text/javascript">
        $.fn.fileinputBsVersion = "5.2.3";
        $('#editor').markdownEditor({
        useTwemoji: true,
        theme: 'fa5',
        enableSplitMode: true,
        enableLivePreview: false,
        toolbarHeaderL: [
            ['undo', 'redo'],
            ['bold', 'italic','del','blockquote'],
            ['link', 'image','codeblock'],['emoji']
        ],
        toolbarFooterL: [],
        toolbarFooterR: ['mode'],
            markdownItOptions: {}
        });
    </script>
```

my js version jQuery v3.6.4

does not work with bootstrap js 5 forced to put version Bootstrap v4.4.1 for it to work 

![Capture d'écran 2023-05-01 070836](https://user-images.githubusercontent.com/8920228/235409635-d208c485-f858-4e06-ad3d-d6e8c57e3054.png)

**Comment by kartik-v** [comment]
You are setting a wrong property. For Krajee markdown editor either set 
1. the `bsVersion` property of the plugin for each plugin specific config --- OR
2. the `$.fn.markdownEditorBsVersion` at a global level for the page (you have wrongly set  `$.fn.fileinputBsVersion` which is for bootstrap-fileinput plugin from Krajee and not this plugin ) 

Check the [configuration examples](https://plugins.krajee.com/markdown-editor#usage-step-1).
