### ISSUE TITLE
Underline button has the wrong tooltip...I think

### ISSUE THREAD

**Issue by Abrahamlet** [kartik-v/krajee-markdown-editor#2]
When one hovers over the underline button, its tooltip says "Inserted Text". I'm thinking it should say "Underline" or something like that.

**Comment by kartik-v** [comment]
Actually `<ins>` tag is rendered when you click that button which is semantically recent (for **inserted text**) while `<u>` tag is an earlier HTML specification for underline. May need to check and see if it can be set to underline to simplify.
